### ISSUE TITLE
meme is bad

### ISSUE THREAD

**Issue by gvmii** [Aniell4/Aniell4#1]
meme is bad !! change for better meme https://cdn.discordapp.com/attachments/926285735160582234/934845320905523241/aniellisscaredoflibraries.png

**Comment by Aniell4** [comment]
**_

- [x] - [1. > _`[amogus](`### url`)`_](url)

_**

**Comment by gvmii** [comment]
i made beter meme for you :(

**Comment by Aniell4** [comment]
but i like more worse meme tho
